using System.Collections;
using System.Collections.Generic;
using UnityEngine;

 public class Mermi : MonoBehaviour
{
    
   
    public float laserSpeed = 10f; //Lazerin gidiț hęzę
    
    [SerializeField]
    private float destroytimeformermi = 5; //Lazerin hayatta kalma süresi

    void Update()
    {
        transform.position = transform.position + new Vector3(0, laserSpeed * Time.deltaTime, 0); // Lazer atęldęktan sonra 'y' ekseninde hareket etmesi
        Destroy(gameObject,destroytimeformermi); // oluțturulan lazerin belirli bir süre sonra yok edilmesi
    }

   
    
}